services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Leuchtfeuer\Mautic\:
    resource: '../Classes/*'

  Leuchtfeuer\Mautic\Hooks\MauticFormHook:
    public: true

  Leuchtfeuer\Mautic\UserFunctions\Tracking:
    public: true

  Leuchtfeuer\Mautic\EventListener\SynchronizeMauticData:
    tags:
      - name: event.listener
        identifier: synchronizeMauticData
        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent

  Leuchtfeuer\Mautic\EventListener\AssignMauticTagsListener:
    tags:
      - name: event.listener
        identifier: mautic.assignTags
        event: TYPO3\CMS\Frontend\Event\AfterPageWithRootLineIsResolvedEvent

  Leuchtfeuer\Mautic\EventListener\MauticFormPreviewListener:
    tags:
      - name: event.listener
        identifier: mautic.formPreview
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent

  Leuchtfeuer\Mautic\EventListener\SetPreferredLocaleListener:
    tags:
      - name: event.listener
        identifier: mautic.setLocale
        event: TYPO3\CMS\Frontend\Event\AfterPageAndLanguageIsResolvedEvent
